name: Azure CI/CD Test Pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Ladda ner koden till roboten
        uses: actions/checkout@v4

      - name: Logga in mot Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Bygg nätverket i Azure
        run: |
          echo "1. Förbereder en låda (Resursgrupp) för nätverket..."
          az group create --name "rg-bicep-network-test" --location "northeurope"
          
          echo "2. Rullar ut Bicep-koden..."
          az deployment group create --resource-group "rg-bicep-network-test" --template-file ./07-bicep/network.bicep